version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    filters:
      branches:
        only:
          - master
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - deploy.sh
            - Dockerfile
            - nginx.conf
  push:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run: apt-get update
      - run: apt-get install -y curl
      - run: chmod +x ./deploy.sh
      - run: sh ./deploy.sh
workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
