version: 2.1
orbs:
  gcr: circleci/gcp-gcr@0.6.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - deploy.sh
            - Dockerfile
            - nginx.conf
  push:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run: apt-get update
      - run: apt-get install -y curl
      - run: chmod +x ./deploy.sh
      - run: sh ./deploy.sh
  build_staging:
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: incognito-web
          tag: $(echo $CIRCLE_SHA1 | cut -c -7)
          dockerfile: staging.Dockerfile
          extra_build_args: --build-arg CONF_ENV
      - gcr/push-image:
          image: incognito-web
          tag: $(echo $CIRCLE_SHA1 | cut -c -7)
  deploy_staging:
    docker:
      - image: gcr.io/staging-incognito/deployer
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
        environment:
          RELEASE: incognito-web
          NAMESPACE: default
    working_directory: /etc/deployments
    steps:
      - run: bash deploy.sh
workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - push:
          requires:
            - build
  deploy_staging:
    jobs:
      - build_staging:
          filters:
            branches:
              only:
                - develop
      - deploy_staging:
          requires:
            - build_staging
          filters:
            branches:
              only:
                - develop
