# This is a basic workflow to help you get started with Actions

name: staging-branch-auto-build-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feature/buy-node-ver2 ]
  pull_request:
    branches: [ feature/buy-node-ver2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: incognito-website-node
    permissions:
      packages: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Prepare tagging data
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "IMAGE_TAGS=$IMAGE_ID:$VERSION,$IMAGE_ID:$GITHUB_RUN_ID" >> $GITHUB_ENV
      -
        name: Build and push image to github packages
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BUILD_ENV=staging
          push: true
          tags: ${{ env.IMAGE_TAGS }}
          labels: "runnumber=${GITHUB_RUN_ID}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: executing remote ssh commands to rollout new version
        uses: appleboy/ssh-action@master
        with:
          context: .
          host: ${{ secrets.STAGING_REMOTE_SSH_HOST }}
          username: ${{ secrets.STAGING_REMOTE_SSH_USER }}
          key: ${{ secrets.STAGING_REMOTE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.STAGING_REMOTE_SSH_PORT }}
          script: |
            kubectl -n incognito-webapp-staging set image deployment.apps/web-node main-container=${{ env.IMAGE_ID }}:${{ env.GITHUB_RUN_ID }} --record
            kubectl -n incognito-webapp-staging annotate --overwrite deployment web-node github_run_number=${{env.GITHUB_RUN_NUMBER}}
            kubectl -n incognito-webapp-staging annotate --overwrite deployment web-node github_run_id=${{env.GITHUB_RUN_ID}}
            kubectl -n incognito-webapp-staging rollout status deployment.apps/web-node
